### PR TITLE
Should Pytorch Provide Performance Hints

### PR DESCRIPTION
**Pull request by msaroufim**
@chauhang @HamidShojanazeri @gdankel @dzhulgakov @jerryzh168

### CODE REVIEW

**Comment by albanD** [comment]
Hey,
Thanks for writing all of this down!

Most of these suggestions seem to be related to extension libraries or specific models that don't live into core.
Could you give some details of where you would expect this kind of package to live?  Would it be a third party repo that would get imported in the user code and would start monitoring third party library usage and also provide some APIs for the user to monitor their code?

**Comment by msaroufim** [comment]
Hi @albanD it depends on the suggestion but my thinking is 

* Pytorch Distributed handles whether you are using it correctly
* HuggingFace tells you that you're overpadding or you could use a slower model
* Pytorch or Pytorch Profileer tells you your accelerator utilization is low
* Torchserve tells you that you can use quantization but maybe even Pytorch?
* torch.device could hold more optimization related data
* Pytorch tells you to set number of threads to 1 on CPU and tells you that batch size needs to be powers of 2

**Comment by albanD** [comment]
That sounds like a lot of different things the users needs to know about to get that information?
In particular because most of these checks wouldn't be enabled by default (because they would be too spammy or too expensive to run).
Wouldn't a third party repo that would be a one place for all of these be easier to use from a user perspective?

**Comment by msaroufim** [comment]
Yeah that's precisely the problem that motivated me to write this. But now that you mention it, it seems like the natural place for a lot of these ideas is either in Pytorch Profiler where people are opting in to get verbose advice

**Comment by msaroufim** [comment]
Closed to discuss this internally first

**Comment by soumith** [comment]
I think the precise thing to discuss here is how to maintain and manage these heuristics that we throw out as part of the PyTorch Profiler (if we accept this PR).

The social aspects of it, the robustness of the suggestions, how one accepts or rejects a suggestion as part of someone contributing it in a PR, if these suggestions are related to non-core libraries, how one handles mainstream ecosystem libraries vs obscure ecosystem libraries, etc. are all important, challenging and need some proposed thoughts.

**Pull request closed without merging**
